### ISSUE TITLE
Update readme with usage

### ISSUE THREAD

**Issue by SimenB** [watilde/meant#1]
I'd love to see the API documented in the readme 🙂

**Comment by watilde** [comment]
Sure! I will add them :)

**Comment by SimenB** [comment]
Awesome! I just looked at npm's implementation and got it to work (pretty simple API after all), but having it in the readme would be sweet 🙂

(where I used it: https://github.com/af/envalid/pull/50)

**Comment by watilde** [comment]
Docs update was released as `v1.0.1`. See the API section at the README.md:
> https://github.com/watilde/meant#api

If the docs are not enough, feel free to reopen this issue. Cheers!

**Comment by SimenB** [comment]
Perfect, thanks!
